import { sqlite } from '../db/client.js'

/**
 * Cross-Platform Alert Generation
 * Creates alerts for all marketplaces based on their specific metrics
 */

export function generateMeeshoAlerts() {
  const alerts = []

  // Alert: Low rating
  const lowRating = sqlite.prepare(`
    SELECT body_json FROM raw_ingest
    WHERE marketplace = 'meesho' AND payload_type = 'overview'
    AND received_at >= datetime('now', '-1 day')
    ORDER BY received_at DESC LIMIT 1
  `).get() as any

  if (lowRating) {
    const data = JSON.parse(lowRating.body_json)
    if (data.kpis?.avg_rating && data.kpis.avg_rating < 3.5) {
      alerts.push({
        rule_id: 'meesho_low_rating',
        severity: 'red',
        title: `Meesho: Low average rating (${data.kpis.avg_rating}★)`,
        message: `Rating is below 3.5 star threshold. Check product quality and customer reviews.`,
        action: 'Review customer feedback and improve product quality or listings.',
        marketplace: 'meesho',
      })
    }
  }

  // Alert: Low impressions trend
  const impressions = sqlite.prepare(`
    SELECT json_extract(body_json, '$.kpis.impressions_7d') as imp
    FROM raw_ingest
    WHERE marketplace = 'meesho' AND payload_type = 'overview'
    ORDER BY received_at DESC LIMIT 2
  `).all() as any[]

  if (impressions.length >= 2) {
    const curr = parseInt(impressions[0].imp) || 0
    const prev = parseInt(impressions[1].imp) || 1
    if (curr > 0 && curr < prev * 0.7) {
      alerts.push({
        rule_id: 'meesho_low_impressions',
        severity: 'amber',
        title: `Meesho: Impressions declined 30%`,
        message: `Previous: ${prev} → Current: ${curr}. Check keyword visibility.`,
        action: 'Increase keyword bids or update product listings.',
        marketplace: 'meesho',
      })
    }
  }

  return alerts
}

export function generateSnapdealAlerts() {
  const alerts = []

  const overviewData = sqlite.prepare(`
    SELECT body_json FROM raw_ingest
    WHERE marketplace = 'snapdeal' AND payload_type = 'overview'
    AND received_at >= datetime('now', '-1 day')
    ORDER BY received_at DESC LIMIT 1
  `).get() as any

  if (overviewData) {
    const data = JSON.parse(overviewData.body_json)

    if (data.kpis?.live && data.kpis.live < 10) {
      alerts.push({
        rule_id: 'snapdeal_low_live_listings',
        severity: 'red',
        title: `Snapdeal: Only ${data.kpis.live} live listings`,
        message: `Catalog size is too small. Expand product range.`,
        action: 'Add more products to increase market presence.',
        marketplace: 'snapdeal',
      })
    }

    if (data.open_alerts?.critical && data.open_alerts.critical > 5) {
      alerts.push({
        rule_id: 'snapdeal_critical_alerts',
        severity: 'red',
        title: `Snapdeal: ${data.open_alerts.critical} critical alerts`,
        message: `Multiple policy or quality issues detected.`,
        action: 'Address critical alerts immediately.',
        marketplace: 'snapdeal',
      })
    }
  }

  return alerts
}

export function generateFlipkartAlerts() {
  const alerts = []

  const businessHealth = sqlite.prepare(`
    SELECT body_json FROM raw_ingest
    WHERE marketplace = 'flipkart' AND payload_type = 'overview'
    AND received_at >= datetime('now', '-1 day')
    ORDER BY received_at DESC LIMIT 1
  `).get() as any

  if (businessHealth) {
    const data = JSON.parse(businessHealth.body_json)
    const bh = data.account_metrics?.business_health || {}

    // Alert: High RTO rate
    if (bh.rto_pct && bh.rto_pct > 10) {
      alerts.push({
        rule_id: 'flipkart_high_rto',
        severity: 'red',
        title: `Flipkart: High RTO rate (${bh.rto_pct}%)`,
        message: `Return-to-origin rate exceeds 10%. Operational issue.`,
        action: 'Improve packaging, check shipping partners, reduce OOD (out-of-delivery) issues.',
        marketplace: 'flipkart',
      })
    }

    // Alert: High cancellation rate
    if (bh.pre_dispatch_cancel_pct && bh.pre_dispatch_cancel_pct > 5) {
      alerts.push({
        rule_id: 'flipkart_high_cancellation',
        severity: 'amber',
        title: `Flipkart: High cancellation rate (${bh.pre_dispatch_cancel_pct}%)`,
        message: `Pre-dispatch cancellations exceed healthy 5% level.`,
        action: 'Review inventory accuracy and order fulfillment process.',
        marketplace: 'flipkart',
      })
    }

    // Alert: Low conversion rate
    if (bh.conversion_7d_pct && bh.conversion_7d_pct < 0.5) {
      alerts.push({
        rule_id: 'flipkart_low_conversion',
        severity: 'amber',
        title: `Flipkart: Low conversion rate (${bh.conversion_7d_pct}%)`,
        message: `Below healthy benchmark of 0.5-1%. Review product pages and pricing.`,
        action: 'Optimize product listings, improve images, adjust pricing strategy.',
        marketplace: 'flipkart',
      })
    }
  }

  return alerts
}

export function generateAmazonAlerts() {
  // Amazon alerts are generated by existing system
  // This function just returns empty - Amazon uses fact_account_health data
  return []
}

export async function runAllPlatformAlerts() {
  console.log('[platform-alerts] Generating alerts for all platforms...')

  try {
    const alerts = [
      ...generateAmazonAlerts(),
      ...generateMeeshoAlerts(),
      ...generateSnapdealAlerts(),
      ...generateFlipkartAlerts(),
    ]

    // Store all alerts
    const now = new Date()
    for (const alert of alerts) {
      const alertId = `alert_${alert.marketplace}_${Date.now()}_${Math.random().toString(36).slice(2, 9)}`
      sqlite.prepare(`
        INSERT INTO alerts (
          id, marketplace, rule_id, scope_type, scope_id, title, message, suggested_action,
          evidence_json, severity, fired_at, status
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
      `).run(
        alertId,
        alert.marketplace || 'amazon_in',
        alert.rule_id,
        'platform',
        alert.marketplace || 'amazon_in',
        alert.title,
        alert.message,
        alert.action,
        JSON.stringify(alert),
        alert.severity,
        now.toISOString(),
        'open'
      )
    }

    console.log(`[platform-alerts] Generated ${alerts.length} alerts`)
    return { alerts_generated: alerts.length, by_marketplace: alerts.length }
  } catch (err) {
    console.error('[platform-alerts] Error:', err)
    return { error: String(err) }
  }
}
